//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class SCHEIDSRECHTER
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SCHEIDSRECHTER()
    {
        this.WEDSTRIJDs = new HashSet<WEDSTRIJD>();
    }

    public int Id { get; set; }
    public string Scheidsrechter_Voornaam { get; set; }
    public string Scheidsrechter_Tussenvoegsel { get; set; }
    public string Scheidsrechter_Achternaam { get; set; }
    public string Gebruikersnaam { get; set; }
    public string Wachtwoord { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<WEDSTRIJD> WEDSTRIJDs { get; set; }
}

public partial class SCHOOL
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SCHOOL()
    {
        this.SPELERs = new HashSet<SPELER>();
    }

    public int Id { get; set; }
    public string School_Naam { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SPELER> SPELERs { get; set; }
}

public partial class SPELER
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SPELER()
    {
        this.WEDSTRIJD_REGEL = new HashSet<WEDSTRIJD_REGEL>();
    }

    public int Id { get; set; }
    public string Speler_Voornaam { get; set; }
    public string Speler_Tussenvoegsel { get; set; }
    public string Speler_Achternaam { get; set; }
    public int School_Id { get; set; }

    public virtual SCHOOL SCHOOL { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<WEDSTRIJD_REGEL> WEDSTRIJD_REGEL { get; set; }
}

public partial class TOERNOOI
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TOERNOOI()
    {
        this.WEDSTRIJDs = new HashSet<WEDSTRIJD>();
    }

    public int Id { get; set; }
    public string Toernooi_Naam { get; set; }
    public System.DateTime Datum { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<WEDSTRIJD> WEDSTRIJDs { get; set; }
}

public partial class WEDSTRIJD
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public WEDSTRIJD()
    {
        this.WEDSTRIJD_REGEL = new HashSet<WEDSTRIJD_REGEL>();
    }

    public int Id { get; set; }
    public int Ronde { get; set; }
    public string Veld { get; set; }
    public System.TimeSpan Begin_Tijd { get; set; }
    public System.TimeSpan Eind_Tijd { get; set; }
    public Nullable<int> Winnaar_Id { get; set; }
    public int Toernooi_Id { get; set; }
    public int Scheidsrechter_Id { get; set; }

    public virtual SCHEIDSRECHTER SCHEIDSRECHTER { get; set; }
    public virtual TOERNOOI TOERNOOI { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<WEDSTRIJD_REGEL> WEDSTRIJD_REGEL { get; set; }
}

public partial class WEDSTRIJD_REGEL
{
    public int Id { get; set; }
    public int Wedstrijd_Id { get; set; }
    public int Speler_Id { get; set; }
    public Nullable<int> Score { get; set; }

    public virtual SPELER SPELER { get; set; }
    public virtual WEDSTRIJD WEDSTRIJD { get; set; }
}
