//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class TennistoernooiEntities : DbContext
{
    public TennistoernooiEntities()
        : base("name=TennistoernooiEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<SCHEIDSRECHTER> SCHEIDSRECHTERs { get; set; }
    public virtual DbSet<SCHOOL> SCHOOLs { get; set; }
    public virtual DbSet<SPELER> SPELERs { get; set; }
    public virtual DbSet<TOERNOOI> TOERNOOIs { get; set; }
    public virtual DbSet<WEDSTRIJD> WEDSTRIJDs { get; set; }
    public virtual DbSet<WEDSTRIJD_REGEL> WEDSTRIJD_REGEL { get; set; }
}
